var spells_2 = [
  {
    name: "Aganazzar’s Scorcher",
    level: 2,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S, M",
    class: "Sorcerer, Wizard",
    duration: "Instantaneous",
    range: "30 feet",
    description: "(a red dragon’s scale) - A line of roaring flame 30 feet long and 5 feet wide emanates from you in a direction you choose. Each creature in the line must make a Dexterity saving throw. A creature takes 3d8 fire damage on a failed save, or half as much damage on a successful one. When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for each slot level above 2nd."
  },
  {
    name: "Aid",
    level: 2,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S, M",
    class: "Cleric, Paladin",
    duration: "8 Hours",
    range: "30 feet",
    description: "(a tiny strip of white cloth) - Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target’s hit point maximum and current hit points increase by 5 for the duration. When you cast this spell using a spell slot of 3rd level or higher, a target’s hit points increase by an additional 5 for each slot level above 2nd."
  },
  {
    name: "Alter Self",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "V, S",
    class: "Sorcerer,Wizard",
    duration: "Concentration, up to 1 hour",
    range: "Self",
    description: "You assume a different form. When you cast the spell, choose one of the following options, the effects of which last for the duration of the spell. While the spell lasts, you can end one option as an action to gain the benefits of a different one. Aquatic Adaptation. You adapt your body to an aquatic environment, sprouting gills, and growing webbing between your fingers. You can breathe underwater and gain a swimming speed equal to your walking speed.Change Appearance. You transform your appearance. You decide what you look like, including your height, weight, facial features, sound of your voice, hair length, coloration, and distinguishing characteristics, if any. You can make yourself appear as a member of another race, though none of your statistics change. You also don’t appear as a creature of a different size than you, and your basic shape stays the same; if you're bipedal, you can’t use this spell to become quadrupedal, for instance. At any time for the duration of the spell, you can use your action to change your appearance in this way again. Natural Weapons. You grow claws, fangs, spines, horns, or a different natural weapon of your choice. Your unarmed strikes deal 1d6 bludgeoning, piercing, or slashing damage, as appropriate to the natural weapon you chose, and you are proficient with your unarmed strikes. Finally, the natural weapon is magic and you have a +1 bonus to the attack and damage rolls you make using it."
  },
  {
    name: "Animal Messenger (Ritual)",
    level: 2,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "-",
    components: "V, S, M",
    class: "Bard, Druid, Ranger",
    duration: "24 hours",
    range: "30 feet",
    description: "(a morsel of food) - By means of this spell, you use an animal to deliver a message. Choose a Tiny beast you can see within range, such as a squirrel, a blue ray, or a bat. You specify a location, which you must have visited, and a recipient who matches a general description, such as a man or woman dressed in the uniform of the town guard or a red-haired dwarf wearing a pointed hat. You also speak a message of up to twenty-five words. The target beast travels for the duration of the spell towards the specified location, covering about 50 miles per 24 hours for a flying messenger or 25 miles for other animals. When the messenger arrives, it delivers your message to the creature that you described, replicating the sound of your voice. The messenger speaks only to a creature matching the description you gave. If the messenger doesn’t reach its destination before the spell ends, the message is lost, and the beast makes it way back to where you cast this spell. If you cast this spell using a spell slot of 3rd level or higher, the duration of the spell increases by 48 hours for each slot level above 2nd."
  },
  {
    name: "Arcane Lock",
    level: 2,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S, M",
    class: "Wizard",
    duration: "Until dispelled",
    range: "Touch",
    description: "(gold dust worth at least 25 gp, which the spell consumes) - You touch a closed door, window, gate, chest, or other entryway, and it becomes locked for the duration. You and the creatures you designate when you cast this spell can open the object normally. You can also set a password that, when spoken within 5 feet of the object, suppresses this spell for 1 minute. Otherwise, it is impassable until it is broken or the spell is dispelled or suppressed. Casting knock on the object suppresses arcane lock for 10 minutes. While affected by this spell, the object is more difficult to break or force open; the DC to break it or pick any locks on it increases by 10."
  },
  {
    name: "Augury (Ritual)",
    level: 2,
    school: "Divination",
    casting_time: "1 Minute",
    ritual: "Yes",
    concentration: "-",
    components: "V, S, M",
    class: "Cleric",
    duration: "Instantaneous",
    range: "Self",
    description: "(specially marked sticks, bones, or similar tokens worth at least 25 gp) - By casting gem-inlaid sticks, rolling dragon bones, laying out ornate cards, or employing some other divining tool, you receive an omen from an otherworldly entity about the results of a specific course of action that you plan to take within the next 30 minutes. The DM chooses from the following possible omens: Weal, for good results; Woe, for bad results; Weal and woe, for both good and bad results; Nothing, for results that aren’t especially good or bad. The spell doesn’t take into account any possible circumstances that might change the outcome, such as the casting of additional spells or the loss or gain of a companion. If you cast the spell two or more times before completing your next long rest, there is a cumulative 25 percent chance for each casting after the first that you get a random reading. The DM makes this roll in secret."
  },
  {
    name: "Barkskin",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "V, S, M",
    class: "Druid, Ranger",
    duration: "Concentration, up to 1 hour",
    range: "Touch",
    description: "(A handful of oak bark) - You touch a willing creature. Until the spellends, the target’s skin has a rough, bark-like appearance, and the target’s AC can’t be less than 16, regardless of what kind of armor it is wearing."
  },
  {
    name: "Beast Sense (Ritual)",
    level: 2,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "Yes",
    components: "S",
    class: "Druid, Ranger",
    duration: "Concentration, up to 1 hour",
    range: "Touch",
    description: "You touch a willing beast. For the duration of the spell, you can use your action to see through the beast’s eyes and hear what it hears, and continue to do so until you use your action to return to your normal senses."
  },
  {
    name: "Blindness/Deafness",
    level: 2,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V",
    class: "Bard, Cleric, Sorcerer, Wizard",
    duration: "1 minute",
    range: "30 feet",
    description: "You can blind or deafen a foe. Choose one creature that you can see within range to make a Constitution saving throw. If it fails, the target is either blinded or deafened (your choice) for the duration. At the end of each of its turns, the target can make a Constitution saving throw. On a success, the spell ends. When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd."
  },
  {
    name: "Blur",
    level: 2,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "V",
    class: "Sorcerer, Wizard",
    duration: "Concentration, up to 1 minute",
    range: "Self",
    description: "Your body becomes blurred, shifting and wavering to all who can see you. For the duration, any creature has disadvantage on attack rolls against you. An attacker is immune to this effect if it doesnt rely on sight, as with blindsight, or can see through illusions, as with truesight."
  },
  {
    name: "Branding Smite",
    level: 2,
    school: "Evocation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "V",
    class: "Paladin",
    duration: "Concentration, up to 1 minute",
    range: "Self",
    description: "The next time you hit a creature with a weapon attack before this spell ends, the weapon glemas with astral radiance as you strike. The attack deals an extra 2d6 radiant damage to the target, which becomes visible if it is invisible, and the target sheds dim light in a 5-foot radius and can’t become invisible until the spell ends. When you cast this spell using a spell slot of 3rd level or higher, the extra damage increases by 1d6 for each slot level above 2nd."
  },
  {
    name: "Calm Emotions",
    level: 2,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "V, S",
    class: "Bard, Cleric",
    duration: "Concentration, up to 1 minute",
    range: "60 feet",
    description: "You attempt to suppress strong emotions in a group of people. Each humanoid in a 20-foot-radius sphere centered on a point you choose within range must make a Charisma saving throw; a creature can choose to fail this saving throw if it wishes. If a creature fails its saving throw, choose one of the following two effects. You can suppress any effect causing a target to be charmed or frightened. When this spell ends, any suppressed effect resumes, provided that its duration has not expired in the meantime. Alternatively, you can make a target indifferent about creatures of your choice that it is hostile toward. This indifference ends if the target is attacked or harmed by a spell or if it witnesses any of its friends being harmed. When the spell ends, the creature becomes hostile again, unless the DM rules otherwise."
  },
  {
    name: "Cloud of Daggers",
    level: 2,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "V, S, M",
    class: "Bars, Sorcerer, Warlock, Wizard",
    duration: "Concentration, up to 1 minute",
    range: "60 feet",
    description: "(a sliver of glass) - You fill the air with spinning daggers in a cube 5 feet on each side, centered on a point you choose within range. A creature takes 4d4 slashing damage when it enters the spell’s area for the first time on a turn or starts its turn there. When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 2d4 for each slot level above 2nd."
  }
];
