var spells_0 = [
  {
    name: "Acid Splash",
    level: 0,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Sorcerer, Wizard",
    duration: "Instantaneous",
    range: "20 feet",
    description: "<p>You hurl a bubble of acid. Choose one creature within range, or choose two creatures within range that are within 2 meter of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage.</p><h4>Higher level</h4><p>This spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).</p>"
  },
  {
    name: "Blade Ward",
    level: 0,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Bard, Sorcerer, Warlock, Wizard",
    duration: "1 Round",
    range: "Self",
    description: "<p>You extend your hand and trace a sigil of warding in the air. Until the end of your next turn, you have resistance against bludgeoning, piercing, and slashing damage dealt by weapon attacks.</p>"
  },
  {
    name: "Booming Blade",
    level: 0,
    shool: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, M",
    class: "Sorcerer, Warlock, Wizard",
    duration: "1 Round",
    range: "2 meter",
    description: "<p>As part of the action used to cast this spell, you must make a melee attack with a weapon against one creature within the spell's range, otherwise the spell fails. On a hit, the target suffers the attack's normal effects, and it becomes sheathed in booming energy until the start of your next turn. If the target willingly moves before then, it immediately takes 1d8 thunder damage, and the spell ends.</p><h4>Higher level</h4><p>At 5th level, the melee attack deals an extra 1d8 thunder damage to the target, and the damage the target takes for moving increases to 2d8. Both damage rolls increase by 1d8 at 11th level and 17th level.</p><h4>Requires:</h4><p>A weapon</p>"
  },
  {
    name: "Chill Touch",
    level: 0,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Sorcerer, Warlock, Wizard",
    duration: "1 Round",
    range: "40 meter",
    description: "<p>You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack against the creature to assail it with the chill of the grave. On a hit, the target takes 1d8 necrotic damage, and it can’t regain hit points until the start of your next turn. Until then, the hand clings to the target. If you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn.</p><h4>Higher level</h4><p>This spell’s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).</p>"
  },
  {
    name: "Control Flames",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "S",
    class: "Druid, Sorcerer, Wizard",
    duration: "1 Hour",
    range: "20 meter",
    description: "<p>You choose non magical flame that you can see within range and that fits within a 2-meter cube. You affect it in one of the following ways:</p><ul><li>You instantaneously expand the flame 2 meter in one direction, provided that wood or other fuel is present in the new location.</li><li>You instantaneously extinguish the flames within the cube.</li><li>You double or halve the area of bright light and dim light cast by the flame, change its color, or both. The change lasts for 1 hour.</li><li>You cause simple shapes—such as the vague form of a creature, an inanimate object, or a location—to appear within the flames and animate as you like.</li></ul><p>The shapes last for 1 hour. If you cast this spell multiple times, you can have up to three of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.</p>"
  },
  {
    name: "Create Bonfire",
    level: 0,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "V, S",
    class: "Druid, Sorcerer, Warlock, Wizard",
    duration: "Concentration, up to 1 minute",
    range: "20 meter",
    description: "<p>You create a bonfire on ground that you can see within range. Until the spells ends, the bonfire fills a 2-meter cube. Any creature in the bonfire’s space when you cast the spell must succeed on a Dexterity saving throw or take 1d8 fire damage. A creature must also make the saving throw when it enters the bonfire’s space for the first time on a turn or ends its turn there.</p><h4>Higher level</h4><p>The spell’s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).</p>"
  },
  {
    name: "Dancing Lights",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "V, S, M",
    class: "Bard, Sorcerer, Wizard",
    duration: "Concentration, up to 1 minute",
    range: "40 meter",
    description: "<p>You create up to four torch-sized lights within range, making them appear as torches, lanterns, or glowing orbs that hover in the air for the duration. You can also combine the four lights into one glowing vaguely humanoid form of Medium size. Whichever form you choose, each light sheds dim light in a 4-meter radius. As a bonus action on your turn, you can move the lights up to 20 meter to a new spot within range. A light must be within 7 meter of another light created by this spell, and a light winks out if it exceeds the spell’s range.</p><h4>Required</h4></p>A bit of phosphorus or wychwood, or a glowworm</p>"
  },
  {
    name: "Druidcraft",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Druid",
    duration: "Instantaneous",
    range: "10 meter",
    description: "<p>Whispering to the spirits of nature, you create one of the following effects within range:</p><ul><li>You create a tiny, harmless sensory effect that predicts what the weather will be at your location for the next 24 hours. The effect might manifest as a golden orb for clear skies, a cloud for rain, falling snowflakes for snow, and so on. This effect persists for 1 round.</li><li>You instantly make a flower blossom, a seed pod open, or a leaf bud bloom.</li><li>You create an instantaneous, harmless sensory effect, such as falling leaves, a puff of wind, the sound of a small animal, or the faint odor of skunk. The effect  must fit in a 2-meter cube.</li><li>You instantly light or snuff out a candle, a torch, or a small campfire.</li></ul>"
  },
  {
    name: "Eldritch Blast",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Warlock",
    duration: "Instantaneous",
    range: "40 meter",
    description: "<p>A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 force damage.</p><h4>Higher level</h4><p>The spell creates more than one beam when you reach higher levels: Two beams at 5th level. Three beams at 11th level. Four beams at 17th level. You can direct the beams at the same target or at different ones. Make a separate attack roll for each beam.</p>"
  },
  {
    name: "Fire Bolt",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Sorcerer, Wizard",
    duration: "Instantaneous",
    range: "40 meter",
    description: "<p>You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn’t being worn or carried.</p><h4>Higher level</h4><p>This spell’s damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).</p>"
  },
  {
    name: "Friends",
    level: 0,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "S, M",
    class: "Bard, Sorcerer, Warlock, Wizard",
    duration: "Concentration, up to 1 minute",
    range: "Self",
    description: "<p>For the duration, you have advantage on all Charisma checks directed at one creature of your choice that isn’t hostile toward you. When the spell ends, the creature realizes that you used magic to influence its mood and becomes hostile toward you. A creature prone to violence might attack you. Another creature might seek retribution in other ways (at the DM’s discretion), depending on the nature of your interaction with it.</p><h4>Required:</h4><p>A small amount of makeup applied to the face as this spell is cast</p>"
  },
  {
    name: "Frostbite",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Druid, Sorcerer, Warlock, Wizard",
    duration: "Instantaneous",
    range: "20 meter",
    description: "<p>You cause numbing frost to form on one creature that you can see within range. The target must make a Constitution saving throw. On a failed save, the target takes 1d6 cold damage, and it has disadvantage on the next weapon attack roll it makes before the end of its next turn.</p><h4>Higher level</h4><p>The spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).</p>"
  },
  {
    name: "Green-Flame Blade",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, M",
    class: "Sorcerer, Warlock, Wizard",
    duration: "Instantaneous",
    range: "2 meter",
    description: "<p>As part of the action used to cast this spell, you must make a melee attack with a weapon against one creature within the spell's range, otherwise the spell fails. On a hit, the target suffers the attack's normal effects, and green fire leaps from the target to a different creature of your choice that you can see within 2 meter of it. The second creature takes fire damage equal to your spellcasting ability modifier.</p><h4>Higher level</h4><p>At 5th level, the melee attack deals an extra 1d8 fire damage to the target, and the fire damage to the second creature increases to 1d8 + your spellcasting ability modifier. Both damage rolls increase by 1d8 at 11th level and 17th level.</p><h4>Required:</h4><p>A weapon</p>"
  },
  {
    name: "Guidance",
    level: 0,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "V, S",
    class: "Cleric, Druid",
    duration: "Instantaneous",
    range: "Touch",
    description: "<p>You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends.</p>"
  },
  {
    name: "Gust",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Druid, Sorcerer, Wizard",
    duration: "Instantaneous",
    range: "10 meter",
    description: "<p>You seize the air and compel it to create one of the following effects at a point you can see within range:</p><ul><li>One Medium or smaller creature that you choose must succeed on a Strength saving throw or be pushed up to 2 meter away from you</li><li>You create a small blast of air capable of moving one object that is neither held nor carried and that weighs no more than 3kg. The object is pushed up to 4 meter away from you. It isn’t pushed with enough force to cause damage</li><li>You create a harmless sensory affect using air, such as causing leaves to rustle, wind to slam shutters shut, or your clothing to ripple in a breeze.</li></ul>"
  },
  {
    name: "Light",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, M",
    class: "Bard, Cleric, Sorcerer, Wizard",
    duration: "1 Hour",
    range: "Touch",
    description: "<p>You touch one object that is no larger than 4 meter in any dimension. Until the spell ends, the object sheds bright light in a 7-meter radius and dim light for an additional 7 meter. The light can be colored as you like. Completely covering the object with something opaque blocks the light. The spell ends if you cast it again or dismiss it as an action. If you target an object held or worn by a hostile creature, that creature must succeed on a Dexterity saving throw to avoid the spell.</p><h4>Required:</h4><p>A firefly or phosphorescent moss</p>"
  },
  {
    name: "Lightning Lure",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V",
    class: "Sorcerer, Warlock, Wizard",
    duration: "Instantaneous",
    range: "5 meter",
    description: "<p>You create a lash of lightning energy that strikes at one creature of your choice that you can see within range. The target must succeed on a Strength saving throw or be pulled up to 10 feet in a straight line toward you and then take 1d8 lightning damage if it is within 2 meter of you.</p><h4>Higher level</h4><p>This spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).</p>"
  },
  {
    name: "Mage Hand",
    level: 0,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Bard, Sorcerer, Warlock, Wizard",
    duration: "1 Minute",
    range: "10 meter",
    description: "<p>A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it as an action. The hand vanishes if it is ever more than 10 meter away from you or if you cast this spell again. You can use your action to control the hand. You can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item from an open container, or pour the contents out of a vial. You can move the hand up to 10 meter each time you use it. The hand can’t attack, activate magical items, or carry more than 5kg.</p>"
  },
  {
    name: "Magic Stone",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Druid, Warlock",
    duration: "1 Minute",
    range: "Touch",
    description: "<p>You touch one to three pebbles and imbue them with magic. You or someone else can make a ranged spell attack with one of the pebbles by throwing it or hurling it with a sling. If thrown, a pebble has a range of 20 meter. If someone else attacks with a pebble, that attacker adds your spellcasting ability modifier, not the attacker’s, to the attack roll. On a hit, the target takes bludgeoning damage equal to 1d6 + your spellcasting ability modifier. Whether the attack hits or misses, the spell then ends on the stone. If you cast this spell again, the spell ends on any pebbles still affected by your previous casting.</p>"
  },
  {
    name: "Mending",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "-",
    components: "V, S, M",
    class: "Bard, Cleric, Druid, Sorcerer, Wizard",
    duration: "Instantaneous",
    range: "Touch",
    description: "<p>This spell repairs a single break or tear in an object you touch, such as broken chain link, two halves of a broken key, a torn cloack, or a leaking wineskin. As long as the break or tear is no larger than 30 cm in any dimension, you mend it, leaving no trace of the former damage. This spell can physically repair a magic item or construct, but the spell can’t restore magic to such an object.</p>"
  },
  {
    name: "Message",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S, M",
    class: "Bard, Sorcerer, Wizard",
    duration: "1 Round",
    range: "40 meter",
    description: "<p>You point your finger toward a creature within range and whisper a message. The target (and only the target) hears the message and can reply in a whisper that only you can hear. You can cast this spell through solid objects if you are familiar with the target and know it is beyond the barrier. Magical silence, 30 cm of stone, 3 cm of common metal, a thin sheet of lead, or 1 meter of wood blocks the spell. The spell doesn’t have to follow a straight line and can travel freely around corners or through openings.</p>"
  },
  {
    name: "Minor Illusion",
    level: 0,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "S, M",
    class: "Bard, Sorcerer, Warlock, Wizard",
    duration: "1 Minute",
    range: "10 meter",
    description: "<p>You create a sound or an image of an object within range that lasts for the duration. The illusion also ends if you dismiss it as an action or cast this spell again. If you create a sound, its volume can range from a whisper to a scream. It can be your voice, someone else’s voice, a lion’s roar, a beating of drums, or any other sound you choose.</p><p>The sound continues unabated throughout the duration, or you can make discrete sounds at different times before the spell ends. If you create an image of an objectsuch as a chair, muddy footprints, or a small chestit must be no larger than a 2-meter cube. The image can’t create sound, light, smell, or any other sensory effect.</p><p>Physical interaction with the image reveals it to be an illusion, because things can pass through it. If a creature uses its action to examine the sound or image, the creature can determine that it is an illusion with a successful Intelligence (Investigation) check against your spell save DC. If a creature discerns the illusion for what it is, the illusion becomes faint to the creature.</p>"
  },
  {
    name: "Mold earth",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "S",
    class: "Druid, Sorcerer, Wizard",
    duration: "1 Hour",
    range: "10 meter",
    description: "<p>You choose a portion of dirt or stone that you can see within range and that fits within a 2-meter cube. You manipulate it in one of the following ways:</p><ul><li>If you target an area of loose earth, you can instantaneously excavate it, move it along the ground, and deposit it up to 2 meter away. This movement doesn’t have enough force to cause damage.</li><li>You cause shapes, colors, or both to appear on the dirt or stone, spelling out words, creating images, or shaping patterns. The changes last for 1 hour.</li><li>If the dirt or stone you target is on the ground, you cause it to become difficult terrain. Alternatively, you can cause the ground to become normal terrain if it is already difficult terrain. This change lasts for 1 hour. If you cast this spell multiple times, you can have no more than two of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.</li></ul>"
  },
  {
    name: "Poison Spray",
    level: 0,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Druid, Sorcerer, Warlock, Wizard",
    duration: "Instantaneous",
    range: "4 meter",
    description: "<p>You extend your hand toward a creature you can see within range and project a puff of noxious gas from your palm. The creature must succeed on a Constitution saving throw or take 1d12 poison damage.</p><h4>Higher level</h4><p>This spell’s damage increases by 1d12 when you reach 5th level (2d12), 11th level (3d12), 17th level (4d12).</p>"
  },
  {
    name: "Prestidigitation",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Bard, Sorcerer, Warlock, Wizard",
    duration: "1 Hour",
    range: "4 meter",
    description: "<p>This spell is a minor magical trick that novice spellcasters use for practice. You create one of the following magical effects within range:</p><ul><li>You create an instantaneous, harmless sensory effect, such as a shower of sparks, a puff of wind, faint musical notes, or an odd odor.</li><li>You instantaneously light or snuff out a candle, a torch, or a small campfire.</li><li>You instantaneously clean or soil an object no larger than 30 cubic cm.</li></li>You chill, warm, or flavor up to 30 cubic cm of nonliving material for 1 hour.</li></li> You make a color, a small mark, or a symbol appear on an object or a surface for 1 hour.</li></li>You create a nonmagical trinket or an illusory image that can fit in your hand and that lasts until the end of your next turn.</li></ul><p>If you cast this spell multiple times, you can have up to three of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.</p>"
  },
  {
    name: "Produce Flame",
    level: 0,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Druid",
    duration: "10 Minutes",
    range: "Self",
    description: "<p>A flickering flame appears in your hand. The flame remains there for the duration and harms neither you nor your equipment. The flame sheds bright light in a 4-meter radius and dim light for an additional 4 meter. The spell ends if you dismiss it as an action or if you cast it again. You can also attack with the flame, although doing so ends the spell. When you cast this spell, or as an action on a later turn, you can hurl the flame at a creature within 10 meter of you. Make a ranged spell attack. On a hit, the target takes 1d8 fire damage.</p><h4>Higher level</h4><p>This spell’s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).</p>"
  },
  {
    name: "Ray of Frost",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Sorcerer, Wizard",
    duration: "Instantaneous",
    range: "20 meter",
    description: "<p>A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, it takes 1d8 cold damage, and its speed is reduced by 4 meter until the start of your next turn.</p><h4>Higher level</h4><p>The spell’s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).</p>"
  },
  {
    name: "Resistance",
    level: 0,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "V, S, M",
    class: "Cleric, Druid",
    duration: "1 Minute",
    range: "Touch",
    description: "<p>You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one saving throw of its choice. It can roll the die before or after the saving throw. The spell then ends.</p>"
  },
  {
    name: "Sacred Flame",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Cleric",
    duration: "Instantaneous",
    range: "20 meter",
    description: "<p>Flame-like radiance descends on a creature that you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage. The target gains no benefit from cover for this saving throw.</p><h4>Higher level</h4><p>The spell’s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).</p>"
  },
  {
    name: "Shape Water",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "S",
    class: "Druid, Sorcerer, Wizard",
    duration: "Instantaneous",
    range: "10 meter",
    description: "<p>You choose an area of water that you can see within range and that fits within a 2-meter cube. You manipulate it in one of the following ways:</p><ul><li>You instantaneously move or otherwise change the flow of the water as you direct, up to 2 meter in any direction. This movement doesn’t have enough force to cause damage.</li><li>You cause the water to form into simple shapes and animate at your direction. This change lasts for 1 hour.</li><li>You change the water’s color or opacity. The water must be changed in the same way throughout. This change lasts for 1 hour.</li><li>You freeze the water, provided that there are no creatures in it. The water unfreezes in 1 hour.</li></ul><p>If you cast this spell multiple times, you can have no more than two of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.</p>"
  },
  {
    name: "Shillelagh",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "-",
    components: "V, S, M",
    class: "Druid",
    duration: "1 Minute",
    range: "Touch",
    description: "<p>The wood of a club or quarterstaff you are holding is imbued with nature’s power. For the duration, you can use your spellcasting ability instead of Strength for the attack and damage rolls of melee attacks using that weapon, and the weapon’s damage die becomes a d8. The weapon also becomes magical, if it isn’t already. The spell ends if you cast it again or if you let go of the weapon.</p>"
  },
  {
    name: "Shocking Grasp",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Sorcerer, Wizard",
    duration: "Instantaneous",
    range: "Touch",
    description: "<p>Lightning springs from your hand to deliver a shock to a creature you try to touch. Make a melee spell attack against the target. You have advantage on the attack roll if the target is wearing armor made of metal. On a hit, the target takes 1d8 lightning damage, and it can’t take reactions until the start of its next turn.</p><h4>Higher level</h4><p>At higher level the spell’s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).</p>"
  },
  {
    name: "Spare the Dying",
    level: 0,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S",
    class: "Cleric",
    duration: "Instantaneous",
    range: "Touch",
    description: "<p>You touch a living creature that has 0 hit points. The creature becomes stable. This spell has no effect on undead or constructs.</p>"
  },
  {
    name: "Sword Burst",
    level: 0,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V",
    class: "Sorcerer, Warlock, Wizard",
    duration: "Instantaneous",
    range: "2 meter",
    description: "<p>You create a momentary circle of spectral blades that sweep around you. Each creature within range, other than you, must succeed on a Dexterity saving throw or take 1d6 force damage.</p><h4>Higher level</h4><p>At higher level this spell's damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).</p>"
  },
  {
    name: "Thaumaturgy",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V",
    class: "Cleric",
    duration: "1 Minute",
    range: "10 meter",
    description: "<p>You manifest a minor wonder, a sign of supernatural power, within range. You create one of the following magical effects within range:</p><ul><li>Your voice booms up to three times as loud as normal for 1 minute.</li><li>You cause flames to flicker, brighten, dim, or change color for 1 minute.</li><li>You cause harmless tremors in the ground for 1 minute.</li><li>You create an instantaneous sound that originates from a point of your choice within range, such as a rumble of thunder, the cry of a raven, or ominous whispers.</li><li>You instantaneously cause an unlocked door or window to fly open or slam shut.</li><li>You alter the appearance of your eyes for 1 minute.</li></ul><p>If you cast this spell multiple times, you can have up to three of its 1-minute effects active at a time, and you can dismiss such an effect as an action.</p>"
  },
  {
    name: "Thorn Whip",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V, S, M",
    class: "Druid",
    duration: "Instantaneous",
    range: "10 meter",
    description: "<p>You create a long, vine-like whip covered in thorns that lashes out at your command toward a creature in range. Make a melee spell attack against the target. If the attack hits, the creature takes 1d6 piercing damage, and if the creature is Large or smaller, you pull the creature up to 4 meter closer to you.</p><h4>Higher level</h4><p>At higher level this spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).</p>"
  },
  {
    name: "Thunderclap",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "S",
    class: "Bard, Sorcerer, Druid, Warlock, Wizard",
    duration: "Instantaneous",
    range: "2 meter",
    description: "<p>You create a burst of thunderous sound, which can be heard 34 meter away. Each creature other than you within 2 meter of you must make a Constitution saving throw. On a failed save, the creature takes 1d6 thunder damage.</p><h4>Higher level</h4><p>The spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).</p>"
  },
  {
    name: "True Strike",
    level: 0,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "S",
    class: "Bard, Sorcerer, Warlock, Wizard",
    duration: "1 Minute",
    range: "10 meter",
    description: "<p>You extend your hand and point a finger at a target in range. Your magic grants you a brief insight into the target’s defenses. On your next turn, you gain advantage on your first attack roll against the target, provided that this spell hasn’t ended.</p>"
  },
  {
    name: "Vicious Mockery",
    level: 0,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "-",
    components: "V",
    class: "Bard",
    duration: "Instantaneous",
    range: "20 meter",
    description: "<p>You unleash a string of insults laced with subtle enchantments at a creature you can see within range. If the target can hear you (thought it need not understand you), it must succeed on a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on the next attack roll it makes before the end of its next turn.</p><h4>Higher level</h4><p>At higher level this spell’s damage increases by 1d4 when you reach 5th level (2d4), 11th level (3d4), and 17th level (4d4).</p>"
  }
];
