var spell_data = [
  {
    name: "Abi-Dalzim’s Horrid Wilting",
    level: 8,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Absorb Elements",
    level: 1,
    school: "Abjuration",
    casting_time: "Special",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Acid Splash",
    level: 0,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Aganazzar’s Scorcher",
    level: 2,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Aid",
    level: 2,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Alarm (Ritual)",
    level: 1,
    school: "Abjuration",
    casting_time: "1 Minute",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Alter Self",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Animal Friendship",
    level: 1,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Animal Messenger (Ritual)",
    level: 2,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Animal Shapes",
    level: 8,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Animate Dead",
    level: 3,
    school: "Necromancy",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Animate Objects",
    level: 5,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Antilife Shell",
    level: 5,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Antimagic Field",
    level: 8,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Antipathy/Sympathy",
    level: 8,
    school: "Enchantment",
    casting_time: "1 Hour",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Arcane Eye",
    level: 4,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Arcane Gate",
    level: 6,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Arcane Lock",
    level: 2,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Armor of Agathys",
    level: 1,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Arms of Hadar",
    level: 1,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Astral Projection",
    level: 9,
    school: "Necromancy",
    casting_time: "1 Hour",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Augury (Ritual)",
    level: 2,
    school: "Divination",
    casting_time: "1 Minute",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Aura of Life",
    level: 4,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Aura of Purity",
    level: 4,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Aura of Vitality",
    level: 3,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Awaken",
    level: 5,
    school: "Transmutation",
    casting_time: "8 Hours",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Bane",
    level: 1,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Banishing Smite",
    level: 5,
    school: "Abjuration",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Banishment",
    level: 4,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Barkskin",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Beacon of Hope",
    level: 3,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Beast Bond",
    level: 1,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Beast Sense (Ritual)",
    level: 2,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Bestow Curse",
    level: 3,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Bigby’s Hand",
    level: 5,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Blade Barrier",
    level: 6,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Blade Ward",
    level: 0,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Bless",
    level: 1,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Blight",
    level: 4,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Blinding Smite",
    level: 3,
    school: "Evocation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Blindness/Deafness",
    level: 2,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Blink",
    level: 3,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Blur",
    level: 2,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Bones of the Earth",
    level: 6,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Booming Blade",
    level: 0,
    shool: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Branding Smite",
    level: 2,
    school: "Evocation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Burning Hands",
    level: 1,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Call Lightning",
    level: 3,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Calm Emotions",
    level: 2,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Catapult",
    level: 1,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Chain Lightning",
    level: 6,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Charm Person",
    level: 1,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Chill Touch",
    level: 0,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Chromatic Orb",
    level: 1,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Circle of Death",
    level: 6,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Circle of Power",
    level: 5,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Clairvoyance",
    level: 3,
    school: "Divination",
    casting_time: "10 Minutes",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Clone",
    level: 8,
    school: "Necromancy",
    casting_time: "1 Hour",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Cloud of Daggers",
    level: 2,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Cloudkill",
    level: 5,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Color Spray",
    level: 1,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Command",
    level: 1,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Commune (Ritual)",
    level: 5,
    school: "Divination",
    casting_time: "1 Minute",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Commune with Nature (Ritual)",
    level: 5,
    school: "Divination",
    casting_time: "1 Minute",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Compelled Duel",
    level: 1,
    school: "Enchantment",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Comprehend Languages (Ritual)",
    level: 1,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Compulsion",
    level: 4,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Cone of Cold",
    level: 5,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Confusion",
    level: 4,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Conjure Animals",
    level: 3,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Conjure Barrage",
    level: 3,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Conjure Celestial",
    level: 7,
    school: "Conjuration",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Conjure Elemental",
    level: 5,
    school: "Conjuration",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Conjure Fey",
    level: 6,
    school: "Conjuration",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Conjure Minor Elementals",
    level: 4,
    school: "Conjuration",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Conjure Volley",
    level: 5,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Conjure Woodland Beings",
    level: 4,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Contact Other Plane (Ritual)",
    level: 5,
    school: "Divination",
    casting_time: "1 Minute",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Contagion",
    level: 5,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Contingency",
    level: 6,
    school: "Evocation",
    casting_time: "10 Minutes",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Continual Flame",
    level: 2,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Control Flames",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Control Water",
    level: 4,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Control Weather",
    level: 8,
    school: "Transmutation",
    casting_time: "10 Minutes",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Control Winds",
    level: 5,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Cordon of Arrows",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Counterspell",
    level: 3,
    school: "Abjuration",
    casting_time: "Special",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Create Bonfire",
    level: 0,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Create Food and Water",
    level: 3,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Create or Destroy Water",
    level: 1,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Create Undead",
    level: 6,
    school: "Necromancy",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Creation",
    level: 5,
    school: "Illusion",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Crown of Madness",
    level: 2,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Crusader’s Mantle",
    level: 3,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Cure Wounds",
    level: 1,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Dancing Lights",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Darkness",
    level: 2,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Darkvision",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Daylight",
    level: 3,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Death Ward",
    level: 4,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Delayed Blast Fireball",
    level: 7,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Demiplane",
    level: 8,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Destructive Wave",
    level: 5,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Detect Evil and Good",
    level: 1,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Detect Magic (Ritual)",
    level: 1,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Detect Poison and Disease",
    level: 1,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Detect Thoughts",
    level: 2,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Dimension Door",
    level: 4,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Disguise Self",
    level: 1,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Disintegrate",
    level: 6,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Dispel Evil and Good",
    level: 5,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Dispel Magic",
    level: 3,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Dissonant Whispers",
    level: 1,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Divination (Ritual)",
    level: 4,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Divine Favor",
    level: 1,
    school: "Evocation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Divine Word",
    level: 7,
    school: "Evocation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Dominate Beast",
    level: 4,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Dominate Monster",
    level: 8,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Dominate Person",
    level: 5,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Drawmij’s Instant Summons (Ritual)",
    level: 6,
    school: "Conjuration",
    casting_time: "1 Minute",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Dream",
    level: 5,
    school: "Illusion",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Druidcraft",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Dust Devil",
    level: 2,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Earth Tremor",
    level: 1,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Earthbind",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Earthquake",
    level: 8,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Eldritch Blast",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Elemental Bane",
    level: 4,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Elemental Weapon",
    level: 3,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Enhance Ability",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Enlarge/Reduce",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Ensnaring Strike",
    level: 1,
    school: "Conjuration",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Entangle",
    level: 1,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Enthrall",
    level: 2,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Erupting Earth",
    level: 3,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Etherealness",
    level: 7,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Evard’s Black Tentacles",
    level: 4,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Expeditious Retreat",
    level: 1,
    school: "Transmutation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Eyebite",
    level: 6,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Fabricate",
    level: 4,
    school: "Transmutation",
    casting_time: "10 Minutes",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Faerie Fire",
    level: 1,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "False Life",
    level: 1,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Fear",
    level: 3,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Feather Fall",
    level: 1,
    school: "Transmutation",
    casting_time: "Special",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Feeblemind",
    level: 8,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Feign Death (Ritual)",
    level: 3,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Find Familiar (Ritual)",
    level: 1,
    school: "Conjuration",
    casting_time: "1 Hour",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Find Steed",
    level: 2,
    school: "Conjuration",
    casting_time: "10 Minutes",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Find the Path",
    level: 6,
    school: "Divination",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Find Traps",
    level: 2,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Finger of Death",
    level: 7,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Fire Bolt",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Fire Shield",
    level: 4,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Fire Storm",
    level: 7,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Fireball",
    level: 3,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Flame Arrows",
    level: 3,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Flame Blade",
    level: 2,
    school: "Evocation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Flame Strike",
    level: 5,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Flaming Sphere",
    level: 2,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Flesh to Stone",
    level: 6,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Fly",
    level: 3,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Fog Cloud",
    level: 1,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Forbiddance (Ritual)",
    level: 6,
    school: "Abjuration",
    casting_time: "10 Minutes",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Forcecage",
    level: 7,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Foresight",
    level: 9,
    school: "Divination",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Freedom of Movement",
    level: 4,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Friends",
    level: 0,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Frostbite",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Gaseous Form",
    level: 3,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Gate",
    level: 9,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Geas",
    level: 5,
    school: "Enchantment",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Gentle Repose (Ritual)",
    level: 2,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Giant Insect",
    level: 4,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Glibness",
    level: 8,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Globe of Invulnerability",
    level: 6,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Glyph of Warding",
    level: 3,
    school: "Abjuration",
    casting_time: "1 Hour",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Goodberry",
    level: 1,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Grasping Vine",
    level: 4,
    school: "Conjuration",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Grease",
    level: 1,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Greater Invisibility",
    level: 4,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Greater Restoration",
    level: 5,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Green-Flame Blade",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Guardian of Faith",
    level: 4,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Guards and Wards",
    level: 6,
    school: "Abjuration",
    casting_time: "10 Minutes",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Guidance",
    level: 0,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Guiding Bolt",
    level: 1,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Gust",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Gust of Wind",
    level: 2,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Hail of Thorns",
    level: 1,
    school: "Conjuration",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Hallow",
    level: 5,
    school: "Evocation",
    casting_time: "24 Hours",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Hallucinatory Terrain",
    level: 4,
    school: "Illusion",
    casting_time: "10 Minutes",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Harm",
    level: 6,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Haste",
    level: 3,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Heal",
    level: 6,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Healing Word",
    level: 1,
    school: "Evocation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Heat Metal",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Hellish Rebuke",
    level: 1,
    school: "Evocation",
    casting_time: "Special",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Heroes’ Feast",
    level: 6,
    school: "Conjuration",
    casting_time: "10 Minutes",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Heroism",
    level: 1,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Hex",
    level: 1,
    school: "Enchantment",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Hold Monster",
    level: 5,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Hold Person",
    level: 2,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Holy Aura",
    level: 8,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Hunger of Hadar",
    level: 3,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Hunter’s Mark",
    level: 1,
    school: "Divination",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Hypnotic Pattern",
    level: 3,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Ice Knife",
    level: 1,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Ice Storm",
    level: 4,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Identify (Ritual)",
    level: 1,
    school: "Divination",
    casting_time: "1 Minute",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Illusory Script (Ritual)",
    level: 1,
    school: "Illusion",
    casting_time: "1 Minute",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Immolation",
    level: 5,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Imprisonment",
    level: 9,
    school: "Abjuration",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Incendiary Cloud",
    level: 8,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Inflict Wounds",
    level: 1,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Insect Plague",
    level: 5,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Investiture of Flame",
    level: 6,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Investiture of Ice",
    level: 6,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Investiture of Stone",
    level: 6,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Investiture of Wind",
    level: 6,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Invisibility",
    level: 2,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Jump",
    level: 1,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Knock",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Legend Lore",
    level: 5,
    school: "Divination",
    casting_time: "10 Minutes",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Leomund’s Secret Chest",
    level: 4,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Leomund’s Tiny Hut (Ritual)",
    level: 3,
    school: "Evocation",
    casting_time: "1 Minute",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Lesser Restoration",
    level: 2,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Levitate",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Light",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Lightning Arrow",
    level: 3,
    school: "Transmutation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Lightning Bolt",
    level: 3,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Lightning Lure",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Locate Animals or Plants (Ritual)",
    level: 2,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Locate Creature",
    level: 4,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Locate Object",
    level: 2,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Longstrider",
    level: 1,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Maelstrom",
    level: 5,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Mage Armor",
    level: 1,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Mage Hand",
    level: 0,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Magic Circle",
    level: 3,
    school: "Abjuration",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Magic Jar",
    level: 6,
    school: "Necromancy",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Magic Missile",
    level: 1,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Magic Mouth (Ritual)",
    level: 2,
    school: "Illusion",
    casting_time: "1 Minute",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem Ipsum"
  },
  {
    name: "Magic Stone",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Magic Weapon",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Major Image",
    level: 3,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Mass Cure Wounds",
    level: 5,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Mass Heal",
    level: 9,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Mass Healing Word",
    level: 3,
    school: "Evocation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Mass Suggestion",
    level: 6,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Maximilian’s Earthen Grasp",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Maze",
    level: 8,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Meld into Stone (Ritual)",
    level: 3,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Melf’s Acid Arrow",
    level: 2,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Melf’s Minute Meteors",
    level: 3,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Mending",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Message",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Meteor Swarm",
    level: 9,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Mind Blank",
    level: 8,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Minor Illusion",
    level: 0,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Mirage Arcane",
    level: 7,
    school: "Illusion",
    casting_time: "10 Minutes",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Mirror Image",
    level: 2,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Mislead",
    level: 5,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Misty Step",
    level: 2,
    school: "Conjuration",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Modify Memory",
    level: 5,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Mold earth",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Moonbeam",
    level: 2,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Mordenkainen’s Faithful Hound",
    level: 4,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Mordenkainen’s Magnificent Mansion",
    level: 7,
    school: "Conjuration",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Mordenkainen’s Private Sanctum",
    level: 4,
    school: "Abjuration",
    casting_time: "10 Minutes",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Mordenkainen’s Sword",
    level: 7,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Move Earth",
    level: 6,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Nondetection",
    level: 3,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Nystul’s Magic Aura",
    level: 2,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Otiluke’s Freezing Sphere",
    level: 6,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Otiluke’s Resilient Sphere",
    level: 4,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Otto’s Irresistible Dance",
    level: 6,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Pass Without Trace",
    level: 2,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Passwall",
    level: 5,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Phantasmal Force",
    level: 2,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Phantasmal Killer",
    level: 4,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Phantom Steed (Ritual)",
    level: 3,
    school: "Illusion",
    casting_time: "1 Minute",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Planar Ally",
    level: 6,
    school: "Conjuration",
    casting_time: "10 Minutes",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Planar Binding",
    level: 5,
    school: "Abjuration",
    casting_time: "1 Hour",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Plane Shift",
    level: 7,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Plant Growth",
    level: 3,
    school: "Transmutation",
    casting_time: "Special",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Poison Spray",
    level: 0,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Polymorph",
    level: 4,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Power Word Heal",
    level: 9,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Power Word Kill",
    level: 9,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Power Word Stun",
    level: 8,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Prayer of Healing",
    level: 2,
    school: "Evocation",
    casting_time: "10 Minutes",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Prestidigitation",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Primordial Ward",
    level: 6,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Prismatic Spray",
    level: 7,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Prismatic Wall",
    level: 9,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Produce Flame",
    level: 0,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Programmed Illusion",
    level: 6,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Project Image",
    level: 7,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Protection from Energy",
    level: 3,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Protection from Evil and Good",
    level: 1,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Protection from Poison",
    level: 2,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Purify Food and Drink (Ritual)",
    level: 1,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Pyrotechnics",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Raise Dead",
    level: 5,
    school: "Necromancy",
    casting_time: "1 Hour",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Rary’s Telepathic Bond (Ritual)",
    level: 5,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Ray of Enfeeblement",
    level: 2,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Ray of Frost",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Ray of Sickness",
    level: 1,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Regenerate",
    level: 7,
    school: "Transmutation",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Reincarnate",
    level: 5,
    school: "Transmutation",
    casting_time: "1 Hour",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Remove Curse",
    level: 3,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Resistance",
    level: 0,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Resurrection",
    level: 7,
    school: "Necromancy",
    casting_time: "1 Hour",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Reverse Gravity",
    level: 7,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Revivify",
    level: 3,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Rope Trick",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Sacred Flame",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Sanctuary",
    level: 1,
    school: "Abjuration",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Scorching Ray",
    level: 2,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Scrying",
    level: 5,
    school: "Divination",
    casting_time: "10 Minutes",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Searing Smite",
    level: 1,
    school: "Evocation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "See invisibility",
    level: 2,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Seeming",
    level: 5,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Sending",
    level: 3,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Sequester",
    level: 7,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Shape Water",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Shapechange",
    level: 9,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Shatter",
    level: 2,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Shield",
    level: 1,
    school: "Abjuration",
    casting_time: "Special",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Shield of Faith",
    level: 1,
    school: "Abjuration",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Shillelagh",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Shocking Grasp",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Silence (Ritual)",
    level: 2,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Silent Image",
    level: 1,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Simulacrum",
    level: 7,
    school: "Illusion",
    casting_time: "12 Hours",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Skywrite (Ritual)",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Sleep",
    level: 1,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Sleet Storm",
    level: 3,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Slow",
    level: 3,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Snilloc’s Snowball Swarm",
    level: 2,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Spare the Dying",
    level: 0,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Speak with Animals (Ritual)",
    level: 1,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Speak with Dead",
    level: 3,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Speak with Plants",
    level: 3,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Spider Climb",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Spike Growth",
    level: 2,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Spirit Guardians",
    level: 3,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Spiritual Weapon",
    level: 2,
    school: "Evocation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Staggering Smite",
    level: 4,
    school: "Evocation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Stinking Cloud",
    level: 3,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Stone Shape",
    level: 4,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Stoneskin",
    level: 4,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Storm of Vengeance",
    level: 9,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Storm Sphere",
    level: 4,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Suggestion",
    level: 2,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Sunbeam",
    level: 6,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Sunburst",
    level: 8,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Swift Quiver",
    level: 5,
    school: "Transmutation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Sword Burst",
    level: 0,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Symbol",
    level: 7,
    school: "Abjuration",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Tasha’s Hideous Laughter",
    level: 1,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Telekinesis",
    level: 5,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Telepathy",
    level: 8,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Teleport",
    level: 7,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Teleportation Circle",
    level: 5,
    school: "Conjuration",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Tenser’s Floating Disk (Ritual)",
    level: 1,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Thaumaturgy",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Thorn Whip",
    level: 0,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Thunderclap",
    level: 0,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Thunderous Smite",
    level: 1,
    school: "Evocation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Thunderwave",
    level: 1,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Tidal Wave",
    level: 3,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Time Stop",
    level: 9,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Tongues",
    level: 3,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Transmute Rock",
    level: 5,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Transport via Plants",
    level: 6,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Trap the Soul",
    level: 8,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Tree Stride",
    level: 5,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "True Polymorph",
    level: 9,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "True Resurrection",
    level: 9,
    school: "Necromancy",
    casting_time: "1 Hour",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "True Seeing",
    level: 6,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "True Strike",
    level: 0,
    school: "Divination",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Tsunami",
    level: 8,
    school: "Conjuration",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Unseen Servant (Ritual)",
    level: 1,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Vampiric Touch",
    level: 3,
    school: "Necromancy",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Vicious Mockery",
    level: 0,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Vitriolic Sphere",
    level: 4,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Wall of Fire",
    level: 4,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Wall of Force",
    level: 5,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Wall of Ice",
    level: 6,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Wall of Sand",
    level: 3,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Wall of Stone",
    level: 5,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Wall of Thorns",
    level: 6,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Wall of Water",
    level: 3,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Warding Bond",
    level: 2,
    school: "Abjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Warding Wind",
    level: 2,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Water Breathing (Ritual)",
    level: 3,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Water Walk (Ritual)",
    level: 3,
    school: "Transmutation",
    casting_time: "1 Action",
    ritual: "Yes",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Watery Sphere",
    level: 4,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Web",
    level: 2,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Weird",
    level: 9,
    school: "Illusion",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Whirlwind",
    level: 7,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Wind Walk",
    level: 6,
    school: "Transmutation",
    casting_time: "1 Minute",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Wind Wall",
    level: 3,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Wish",
    level: 9,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Witch Bolt",
    level: 1,
    school: "Evocation",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Word of Recall",
    level: 6,
    school: "Conjuration",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Wrathful Smite",
    level: 1,
    school: "Evocation",
    casting_time: "1 Bonus",
    ritual: "-",
    concentration: "Yes",
    components: "",
    class: "",
    description: "Lorem ipsum"
  },
  {
    name: "Zone of Truth",
    level: 2,
    school: "Enchantment",
    casting_time: "1 Action",
    ritual: "-",
    concentration: "No",
    components: "",
    class: "",
    description: "Lorem ipsum"
  }
];
